<?php

return [
'add_avocado' => 'An avocado is a fruit that is native to South Central kisii, classified as a member of the flowering plant family Lauraceae.',
'how do you eat an avocado?' => 'Avocados can be eaten raw, sliced, mashed, or turned into guacamole. They are versatile and can be used in various dishes such as salads, sandwiches, and smoothies.',
'are avocados nutritious' => 'Yes, avocados are highly nutritious. They are rich in healthy fats, fiber, vitamins, and minerals. Consuming avocados may have various health benefits, including improved heart health and better digestion.',
'where do avocados grow?' => 'Avocados grow on trees in subtropical climates. They are cultivated in many parts of the world, including Mexico, the United States (particularly California and Florida), and parts of Central and South America.',
'hi' => 'What would you\'d like to know?',
'What_grafting' => 'Grafting is a horticultural technique used to join two different plant parts together, the lower part(root stock, often providing root system and stability) and the upper part (the scion ( Often providing desirable characteristics such as fruit quality).It\’s done to ensure early crops, fruit consistency and better quality. 
Grafting also helps to get the desired variety. (Hass, Fuerte...etc.)',
        
'What is grafting, and why its importance?' => 'Grafting is a horticultural technique used to join two different plant parts together, the lower part (root stock, often providing root system and stability) and the upper part (the scion, often providing desirable characteristics such as fruit quality). It’s done to ensure early crops, fruit consistency and better quality. Grafting also helps to get the desired variety. (Hass, Fuerte...etc.) Application: 1. Variety improvement 2. Disease Management 3. Climate adaptation 4. Increased Productivity',

'time_to_transplant_avocado' => 'Regardless of the specific timing, it\'s crucial to transplant avocado seedlings when they are dormant or in a period of low vegetative growth to minimize stress and maximize transplant success. Additionally, ensure that the soil is well-prepared and adequately amended with organic matter to provide optimal growing conditions for the transplanted seedlings. Proper care and attention during the transplanting process can help ensure the healthy establishment and long-term growth of avocado trees.',

'steps_transplanting_avocado' => 'Transplanting avocado seedlings into the soil requires careful preparation and execution to ensure the successful establishment of the young trees. Here are the steps for transplanting avocado seedlings: 1. Prepare the Planting Site: Choose a suitable location for transplanting the avocado seedlings, ensuring it receives full sunlight and has well-drained soil. Dig a planting hole that is wide and deep enough (2ft by 2ft by 2ft). 2. Prepare the Seedlings: Choose seedlings that are hardened that are at least 1 year old since grafting with healed grafting unions. Carefully remove the avocado seedlings from their potting bags, taking care not to damage the roots. Gently loosen the root ball and tease out any circling roots to encourage outward root growth. 3. Place the Seedlings in the Planting Hole: Position the avocado seedling in the center of the planting hole, ensuring that the top of the root ball is level with the surrounding soil surface. Backfill the hole with soil, firming it gently around the roots to eliminate air pockets and provide stability for the seedling. 4. Water the Transplanted Seedlings: After planting, thoroughly water the transplanted avocado seedlings to settle the soil around the roots and provide moisture for initial root growth. Apply water slowly and evenly to ensure thorough saturation of the root zone, but avoid overwatering, which can lead to root rot. 5. Mulch around the Seedlings: Apply a layer of organic mulch, such as wood chips or compost, around the base of the transplanted avocado seedlings. Leave a gap between the mulch and the trunk of the seedlings to prevent moisture buildup and potential rotting. 6. Provide management: Monitor the transplanted avocado seedlings regularly for signs of stress and water as needed to maintain soil moisture. Protect the seedlings from extreme weather conditions, such as strong winds or heavy rain, by providing temporary shelter or windbreaks if necessary. Consider staking taller seedlings to provide support until they become established in the soil.',

'reduce_transplant_shock' => 'Transplant shock can occur when avocado seedlings are moved from their original growing environment, such as a nursery container, to a new location in the soil. Minimizing transplant shock is crucial for the successful establishment of avocado seedlings. Here are some strategies to help reduce transplant shock: 1. Choose the Right Timing: Transplant during periods of cooler weather, such as early spring or late fall, when temperatures are milder and soil moisture is more consistent. Avoid transplanting during extreme heat or cold, as this can stress the seedlings. 2. Handle Seedlings Carefully: When removing avocado seedlings from their nursery containers, handle them gently to avoid damaging the roots or disturbing the soil around the root ball. Try to keep the root system intact as much as possible. 3. Prepare the Planting Hole Properly: Dig a planting hole that is wide and shallow enough to accommodate the root ball of the avocado seedling. Loosen the soil in the planting hole and amend it with organic matter if needed to improve drainage and provide nutrients for root growth. 4. Water Thoroughly Before and After Transplanting: Before transplanting, thoroughly water the avocado seedlings in their nursery containers to hydrate the roots and reduce stress. After transplanting, water again to settle the soil around the roots and provide moisture for initial growth. 5. Avoid Disturbing the Roots: When transplanting avocado seedlings, try to disturb the roots as little as possible. Handle the seedlings carefully and avoid rough handling or excessive shaking, which can damage delicate root hairs and increase transplant shock. 6. Provide Shade and Wind Protection: Newly transplanted avocado seedlings are vulnerable to sunburn and wind damage. Provide temporary shade using shade cloth or plant covers, and protect the seedlings from strong winds with windbreaks or temporary barriers. 7. Monitor and Adjust Watering: Monitor soil moisture levels regularly after transplanting and adjust watering as needed to keep the soil consistently moist but not waterlogged. Avoid letting the soil dry out completely, as this can stress the seedlings. 8. Mulch around Seedlings: Apply a layer of organic mulch around the base of the avocado seedlings to help retain soil moisture, suppress weeds, and regulate soil temperature. Leave a gap between the mulch and the trunk of the seedlings to prevent moisture buildup and potential rotting.',

'when_to_harvest' => 'By looking for signs of maturity which are: 1. Fruit stalk: larger, swollen and distinctly yellow, rather than green 2. Seed coat: dry, dark and somewhat shriveled, rather than pale whitish 3. Skin: dull and lusterless, with a powdery appearance rather than shiny. 4. Fruit: generally larger but not always so, very mature ones will start to go purple on the outside.',

'how_to_harvest' => '1. Timing: Harvest when they are mature but still firm. 2. Gentle Handling: Handle with care to avoid bruising or damaging the fruit. Use a picking pole or ladder to reach higher branches, and gently clip the fruit from the stem, being careful not to pull on the fruit excessively. 3. Harvesting Tools and techniques: Depending on the size and height of the tree, various harvesting tools can be used, including picking poles with baskets or bags attached, hand clippers, or pruning shears. Choose tools that allow for easy and gentle removal of the fruit. 4. Storing and Transporting: After harvesting, carefully place avocados in shallow containers or baskets to prevent them from being crushed. Store them in a cool, well-ventilated area away from direct sunlight until they are ready for further processing.',

'avocado_nutritional_requirements' => 'Avocados need both Macro (Nitrogen, Phosphorus and Potassium) and Micro nutrients (Boron, Zinc, Calcium, Manganese, and Sulphur). They also thrive in soils high in organic matter.',

'how_to_fertilize_avocados' => 'Fertilization is done based on specific avocado needs and nutrition requirements. Normally done during stages of it production cycles. It is feed by either soil applications or foliar sprays and sometimes through the irrigation system.',

'common_pests' => 'Thrips, False Codling Moth, Fruit flies, Scales, Mites, are some of the pests. Anthracnose and root rot.',

'avocado_disease_symptoms' => 'Some of the common symptoms of diseases include 1. Brown or yellow leaf spots 2. Flower or fruit drop 3. Dieback 4. Wilting 5. Trees affected lose vitality, become sparsely foliated and do not produce a good crop Some of the common symptoms of pests 1. Yellow or brown stippling on the upper surface of leaves caused by feeding damage. 2. Leaves may curl or become distorted. 3. Presence of black or dark brown excrement (fecal spots) on leaves. 4. Scarring or scabbing on the fruit surface.',

'pest_and_disease_prevention' => 'Preventing pests and diseases in avocado orchards requires a combination of cultural, biological, and chemical management strategies. Here are some effective methods to help prevent pests and diseases in avocado orchards: 1. Site Selection and Orchard Layout: Choose a site for the avocado orchard that has good drainage, adequate sunlight, and proper air circulation. Plan the orchard layout to maximize airflow between trees, minimize humidity, and facilitate access for pest and disease management practices. 2. Use Certified Disease-Free Planting Material: Start with healthy seedlings or grafted trees from reputable nurseries that have been certified as disease-free. Avoid planting trees that show signs of disease or pest infestation, as they can introduce pathogens and pests into the orchard. 3. Crop Rotation and Interplanting: Rotate avocado crops with non-host crops or cover crops to disrupt pest and disease cycles and reduce the buildup of pathogens and pests in the soil. Interplanting with companion plants that attract beneficial insects or repel pests can also help reduce pest pressure in the orchard. 4. Sanitation Practices: Implement strict sanitation practices in the orchard to remove plant debris, fallen fruit, and weeds that can harbor pests and diseases. Prune dead or diseased branches, and promptly remove and destroy any infected or infested plant material to prevent the spread of pathogens. 5. Monitoring and Early Detection: Regularly monitor for signs of pest infestation, such as leaf damage, fruit damage, or presence of pests. Set up pheromone traps or sticky traps to monitor pest populations, and inspect trees carefully for symptoms of diseases

. Early detection allows for timely intervention and reduces the risk of widespread outbreaks. 6. Biological Control: Encourage the presence of natural predators, parasitoids, and beneficial insects in the orchard by providing suitable habitats and avoiding the use of broad-spectrum pesticides that can harm beneficial organisms. Release beneficial insects or apply biological control agents as needed to manage pest populations. 7. Integrated Pest Management (IPM): Develop and implement an IPM plan that integrates cultural, biological, and chemical control methods to manage pests and diseases effectively. Use targeted, low-toxicity pesticides as a last resort, and follow recommended application rates and timing to minimize environmental impact. 8. Soil and Plant Health: Maintain healthy soil through regular soil testing, proper fertilization, and organic matter addition. Healthy plants are more resilient to pests and diseases. Water trees adequately but avoid overwatering, which can lead to root diseases. 9. Resistant Varieties: Choose avocado varieties that are known to be resistant or tolerant to common pests and diseases in your region. Resistant varieties can reduce the risk of severe infestations and improve overall orchard health. 10. Quarantine Measures: Implement quarantine measures to prevent the introduction and spread of new pests and diseases. Inspect new planting material, equipment, and vehicles entering the orchard for signs of pests or pathogens, and follow proper disinfection protocols as needed.',

'watering_frequency_underwatering_signs' => 'The frequency of watering avocado trees depends on various factors, including the tree\'s age, soil type, climate, and stage of growth. While the watering needs may vary, here are some general guidelines to help determine how often avocado trees should be watered: 1. Newly Planted Trees: Newly planted avocado trees have higher water requirements to establish their root systems. Water the trees immediately after planting and keep the soil consistently moist for the first few weeks. Depending on weather conditions, water every 2-3 days, ensuring the soil remains moist but not waterlogged. 2. Young Trees: For young avocado trees (up to 3 years old), water them deeply once or twice a week during dry periods. Monitor the soil moisture regularly, and adjust the frequency based on the tree\'s water needs and the soil\'s ability to retain moisture. 3. Mature Trees: Mature avocado trees (3 years and older) typically require less frequent watering. Deeply water the trees every 7-10 days during dry periods, allowing the soil to dry slightly between waterings. Ensure the soil is well-drained to prevent waterlogging and root rot. Signs of Overwatering: 1. Yellowing Leaves: Overwatered avocado trees may exhibit yellowing leaves, particularly in the lower canopy. 2. Leaf Drop: Excessive water can cause leaves to drop prematurely. 3. Root Rot: Prolonged overwatering can lead to root rot, resulting in dark, mushy roots. 4. Wilting: Surprisingly, overwatered trees may also wilt due to root damage and lack of oxygen. Signs of Underwatering: 1. Wilting Leaves: Underwatered avocado trees may exhibit wilting or drooping leaves, especially during hot weather. 2. Leaf Curling: Leaves may curl or become dry and brittle due to insufficient water. 3. Leaf Drop: Severe underwatering can cause leaves to drop prematurely. 4. Slow Growth: Underwatered trees may show stunted growth and reduced vigor.',

'avocado_pruning_practices' => '1. Timing: Pruning is done during late winter or early spring. 2. Tools: Using sharp, clean pruning shears. 3. Pruning: Dead, damaged, or diseased branches, as well as any water sprouts or suckers are removed. 4. Shape: Aim to maintain a balanced canopy shape that allows sunlight penetration and air circulation.',

'avocado_soil_management' => 'They grow best in well-drained, sandy loam soils with good organic matter content. The soil pH should be slightly acidic to neutral (6-7). Soil management practices include: 1. Regularly testing soil fertility and nutrient levels. 2. Adding organic matter such as compost to improve soil structure and fertility. 3. Using mulches to conserve soil moisture, regulate temperature, and reduce weed competition. 4. Implementing proper irrigation practices to avoid waterlogging or drought stress. 5. Using cover crops to improve soil health and prevent erosion. 6. Monitoring and controlling soil-borne diseases and pests.',

'avocado_planting_distance' => 'Planting distance for avocado trees depends on factors such as tree size, growth habit, and orchard management practices. Here are some general guidelines for spacing avocado trees: 1. Standard Avocado Trees: Standard avocado trees, which can grow large and have a spreading canopy, typically require more space. Plant standard avocado trees at a distance of 20 to 30 feet (6 to 9 meters) apart. This spacing allows enough room for the trees to grow to their full size without overcrowding. 2. Dwarf or Semi-Dwarf Avocado Trees: Dwarf or semi-dwarf avocado varieties are smaller in size and have a more compact growth habit. These trees can be planted closer together. Plant dwarf or semi-dwarf avocado trees at a distance of 10 to 15 feet (3 to 4.5 meters) apart. This spacing is suitable for home gardens or small orchards. 3. High-Density Planting: In commercial avocado orchards, high-density planting is sometimes used to maximize production in a limited space. This involves planting trees at closer distances, such as 12 to 15 feet (3.6 to 4.5 meters) apart, and using specialized pruning and training techniques to manage the canopy size and shape. 4. Row Spacing: In addition to the distance between individual trees, consider the spacing between rows. For standard avocado trees, row spacing should be 25 to 30 feet (7.5 to 9 meters) apart. For dwarf or semi-dwarf trees, row spacing can be reduced to 15 to 20 feet (4.5 to 6 meters) apart. 5. Orchard Layout: When planning the orchard layout, ensure there is enough space for equipment access, maintenance, and harvesting. Provide adequate space for pathways and access roads between rows. 6. Microclimate and Site Conditions: Take into account the specific site conditions and microclimate of the planting location. Factors such as wind exposure, slope, and soil type can influence the optimal planting distance. Adjust the spacing as needed to accommodate these conditions.',
 
'haas_benefits' => 'Heart Health: Hass avocados are rich in monounsaturated fats, particularly oleic acid, which is known to support heart health by helping to reduce levels of LDL (bad) cholesterol and increase levels of HDL (good) cholesterol. This can contribute to a lower risk of heart disease. Nutrient Density: Avocados are packed with essential nutrients, including vitamins such as vitamin K, vitamin E, vitamin C, and B vitamins (including folate), as well as minerals like potassium and magnesium. These nutrients play vital roles in various bodily functions, including immune function, bone health, and energy metabolism. Fiber Content: Hass avocados are an excellent source of dietary fiber, both soluble and insoluble. Fiber is essential for digestive health, promoting regular bowel movements, preventing constipation, and supporting a healthy gut microbiome. Antioxidant Properties: contain antioxidants such as carotenoids (including lutein and zeaxanthin) and tocopherols (including vitamin E), which help to neutralize harmful free radicals in the body. This may help to reduce inflammation, protect against oxidative stress, and lower the risk of chronic diseases like cancer and neurodegenerative disorders. Skin Health: The monounsaturated fats and antioxidants found in Hass avocados can benefit skin health by moisturizing and nourishing the skin from within. Additionally, the vitamin E content may help to protect the skin from UV damage and promote a youthful complexion. Weight Management: Despite being relatively high in calories, studies suggest that incorporating moderate amounts of avocados into a balanced diet may support weight management. The combination of healthy fats, fiber, and nutrients in avocados can help to increase satiety and reduce cravings for unhealthy snacks.', 

'haas_avocado_growth_cycle' => 'Stages of avocado growth: Starting seeds /germination, Seedlings this is when they are grafted, Getting established /vegetative growth after transplanting to the field, Flowering (It’s worth noting that avocados are intermittent bloomers, so they may not produce flowers and fruits every year), Fruit development, Regrowth this is after the fruits have been harvested and the plant is rejuvenating Preparing for another cycle of fruit production.', 

'haas_avocado_taste_and_texture' => 'The taste of Hass avocados can be described as buttery and slightly nutty, with a smooth and velvety mouthfeel. When perfectly ripe, they have a delicate sweetness with subtle hints of earthiness and a mild tanginess. Overall, the taste of Hass avocados is highly prized by avocado enthusiasts for its unique combination of flavors and textures.', 

'haas_avocado_environmental_and_soil_conditions' => 'Temperature: Warm tropical climate, 20-30 degrees Celsius, can tolerate lows of up to 10 degrees Celsius for a short time. Soil: Well-draining soils such as sandy and loamy with moderate to high organic matter, pH 5.5 -7.0. Water: Consistent water supply, Rainfall of 1000-1200 mm annually. Sunlight: Prefer full sunlight of at least 6 hours a day for optimal growth. Nutrients: Balanced supply of essential nutrients such as nitrogen, phosphorus, potassium. Also require micro nutrients such as zinc, iron, copper, manganese. Relative humidity: 75% -80%. Altitude: 800 -2500 above sea level. Wind: Wind breakers should be established a year before. Pollination: Planting 2 or more varieties close together and bee hives establishment.', 

'pruning_and_importance' => 'Pruning is a horticultural practice that involves selectively removing specific parts of a plant, such as branches, shoots, or roots, to improve its health, shape, and productivity. When it comes to avocado trees, pruning is essential for several reasons, and there are specific tools used for this purpose. Tools Used for Pruning Avocado Trees: Pruning Shears/Secateurs: These are handheld cutting tools with sharp blades used for precise pruning of smaller branches and foliage. Loppers: Loppers are similar to pruning shears but have longer handles and larger blades, allowing for the pruning of thicker branches. Hand Pruning Saws: Hand saws with curved blades are useful for cutting thicker branches that cannot be easily pruned with shears or loppers. Pole Pruners: Pole pruners consist of a long pole with a pruning head attached at the end, allowing for pruning at greater heights without the need for a ladder. Chainsaws: For larger-scale pruning or removal of significant branches, chainsaws may be used, although they require careful handling to avoid damaging the tree. Importance of Pruning Avocado Trees: Promotes Air Circulation: Pruning helps to open up the canopy of the avocado tree, allowing for better air circulation and sunlight penetration throughout the tree. This can help reduce the risk of fungal diseases and improve overall tree health. Controls Tree Size: Avocado trees can grow quite large if left unpruned, which may make harvesting and maintenance difficult. Pruning helps to manage the size of the tree, keeping it at a manageable height for easier access to fruit and maintenance tasks. Encourages Fruit Production: Pruning encourages the development of fruit-bearing wood by removing non-productive branches and redirecting the tree\'s energy towards fruit production. It also promotes the growth of new shoots and branches, which are more likely to bear fruit. Removes Dead or Diseased Wood: Pruning allows for the removal of dead, damaged, or diseased branches, which can harbor pests and diseases and inhibit the tree\'s growth. Removing these branches helps to improve overall tree health and vigor. Shapes the Tree: Pruning can help shape the avocado tree to improve its aesthetic appearance and structure. This can also make maintenance tasks, such as harvesting and pest control, more manageable.', 

'mulching_and_mulching_tools' => 'Role of Mulching in Avocado Cultivation: Moisture Conservation: Mulch helps to retain soil moisture by reducing evaporation from the soil surface. This is particularly beneficial in regions with hot and dry climates or during periods of drought, helping to ensure consistent moisture levels for avocado trees. Weed Control: Mulch acts as a natural weed barrier, suppressing weed growth by blocking sunlight and preventing weed seeds from germinating. This reduces competition for water, nutrients, and sunlight, allowing avocado trees to thrive without being overshadowed by invasive weeds. Soil Temperature Regulation: Mulch helps to moderate soil temperatures by insulating the soil from extreme heat or cold. This creates a more stable and favorable environment for root growth and microbial activity, which is essential for healthy soil and tree development. Soil Erosion Prevention: Mulch helps to prevent soil erosion by reducing surface runoff and promoting infiltration of rainwater into the soil. This helps to protect the soil structure and prevent nutrient loss, particularly on sloped terrain or in areas prone to erosion. Organic Matter Addition: As mulch decomposes over time, it adds organic matter to the soil, enriching soil fertility and promoting microbial activity. This enhances soil structure, water retention, and nutrient availability, supporting healthy root development and overall tree growth.',

'mulching_tools' => 'Common Tools Used for Applying Mulch include: Mulch Spreader: A mulch spreader is a machine designed to evenly distribute mulch over large areas quickly and efficiently. It typically consists of a hopper for holding mulch and a mechanism for spreading it evenly onto the soil surface. Mulch Fork or Rake: A mulch fork or rake is a hand tool with sturdy tines or prongs used for spreading mulch manually. It allows for more precise application of mulch around the base of individual trees and in tight spaces where larger machinery may not reach. Shovel or Pitchfork: A shovel or pitchfork can be used to scoop and distribute mulch around the avocado trees manually. These tools are especially useful for spreading mulch in smaller orchards or areas with limited access for larger equipment. Wheelbarrow: A wheelbarrow is essential for transporting mulch from the storage area to the orchard. It allows for efficient movement of mulch across the orchard while minimizing manual labor. Mulch Blower: In larger avocado orchards or commercial operations, mulch blowers may be used to apply mulch quickly and evenly over large areas. These machines use air pressure to blow mulch onto the soil surface, reducing the need for manual labor and speeding up the mulching process.', 

'avocado_irrigation_tools_and_irrigation_techniques' => 'Specialized irrigation tools and techniques are essential for ensuring optimal water distribution, efficient water use, and healthy tree growth. Some common specialized irrigation tools used include: Drip Irrigation Systems: is widely used in due to its efficiency in delivering water directly to the root zone of trees. Drip emitters or drip lines are installed along the tree rows, delivering water slowly and precisely to the base of each tree. This method reduces water loss due to evaporation and runoff and allows for controlled irrigation scheduling based on tree water requirements. Micro sprinklers: consist of small sprinkler heads mounted on low-pressure pipes or risers, typically placed in the tree canopy or at ground level. They provide a fine mist or spray of water, which can effectively wet the soil surface and foliage while minimizing water drift and evaporation. They are particularly useful for young avocado trees and in areas with sandy soils or high wind conditions. Fertigation Systems: Fertigation combines irrigation and fertilization by delivering nutrients to through the irrigation system. This can be accomplished using specialized fertigation equipment, such as injector pumps, which inject liquid fertilizers or soluble fertilizers into the irrigation water. Fertigation allows for precise nutrient application, ensuring optimal uptake and minimizing nutrient leaching. Soil Moisture Sensors: Soil moisture sensors are used to monitor soil moisture levels in the root zone of avocado trees, providing valuable data for irrigation scheduling and water management decisions. These sensors can be installed at various depths in the soil profile to assess moisture distribution and help optimize irrigation timing and duration based on tree water requirements and soil conditions. Weather-Based Irrigation Controllers: Weather-based irrigation controllers, also known as smart controllers or ET (evapotranspiration) controllers, use weather data such as temperature, humidity, and rainfall to adjust irrigation scheduling automatically. These controllers calculate the water needs of avocado trees based on environmental conditions and plant factors, ensuring efficient water use and reducing the risk of overwatering or under watering. Trickle Tape: Trickle tape is a specialized type of drip irrigation tubing that features pre-installed emitters spaced at regular intervals. It is often used in avocado orchards for subsurface irrigation, where the tape is buried below the soil surface to deliver water directly to the root zone while minimizing evaporation and soil surface wetting.', 

'Avocado_companion_plants' => 'Companion planting involves growing certain plants together to benefit one another by attracting beneficial insects, repelling pests, improving soil health, and providing other advantages. Here are a few companion plants that can be grown alongside avocado trees: Citrus Trees: Citrus trees, such as lemon, lime, and orange, can be compatible companions for avocado trees. They have similar soil and water requirements and can provide a complementary aesthetic in the orchard. Herbs: Certain herbs, such as basil, parsley, and cilantro, can be grown near avocado trees. These herbs may attract beneficial insects and pollinators while also providing culinary benefits for the grower. Flowering Plants: Planting flowering plants, such as marigolds, nasturtiums, and lavender, near avocado trees can attract pollinators like bees and butterflies. Additionally, the strong scent of some flowering plants may help deter pests. Legumes: Nitrogen-fixing legumes, such as beans and peas, can improve soil fertility by adding nitrogen to the soil through their root nodules. Although avocado trees do not fix nitrogen themselves, neighboring legumes can enhance soil health and nutrient availability. Cover Crops: Growing cover crops, such as clover or vetch, between avocado tree rows during the offseason can help improve soil structure, suppress weeds, and provide organic matter when incorporated into the soil. Native Plants: Planting native species of trees, shrubs, and wildflowers in and around avocado orchards can support local ecosystems, attract beneficial wildlife, and promote biodiversity. When selecting companion plants for avocado orchards, it\'s essential to consider factors such as water requirements, soil compatibility, and potential competition for resources. Additionally, avoid planting species that may harbor pests or diseases that could affect avocado trees negatively. Experimenting with different companion plants and observing their interactions with avocado trees can help growers find the best combinations for their specific growing conditions.', 

'Avocado_spacing' => '4m by 4m = 230-250 trees, 5m by 4m = 180-200 trees, 5m by 5m = 140-160 trees, 6m by 5m = 110-130 trees, 6m by 6m = 90-110 trees, 6m by 7m = 76-96 trees, 7m by 7m = 60-80 trees, 7m by 8m = 50-70 trees, 8m by 8m = 43-63 trees.'

    // Add more questions and answers as needed
];
